# This is for the local development environment, so the creds aren't important
version: "3.7"
services:
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - /var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql

    chatscript:
        build:
            context: ./
            dockerfile: Dockerfile-local
        ports:
            - 1024:1024
        volumes:
            - type: bind
              target: /app/ChatScript/RAWDATA
              source: /D/source/PostMortem/ChatScript/RAWDATA
            - type: bind
              target: /app/ChatScript/LOGS
              source: /D/source/PostMortem/ChatScript/LOGS
            - type: bind
              target: /app/ChatScript/USERS
              source: /D/source/PostMortem/ChatScript/USERS