FROM ubuntu:18.04 as chatscript-builder

# Install system packages/dependencies
RUN apt-get --yes update \
 && apt-get --no-install-recommends --yes install git ca-certificates

WORKDIR /src

RUN git clone https://github.com/ianByrne/ChatScript.git

FROM ubuntu:18.04 as chatscript-builder-bot

ARG BOTNAME=OLIVE

# Install system packages/dependencies
RUN apt-get --yes update \
 && apt-get --no-install-recommends --yes install libcurl3 \
 && rm -rf /var/lib/apt/lists/*

# Copy minimal set of ChatScript files
COPY --from=chatscript-builder /src/ChatScript/BINARIES/LinuxChatScript64 /opt/ChatScript/BINARIES/
COPY --from=chatscript-builder /src/ChatScript/DICT/ENGLISH/*.bin /opt/ChatScript/DICT/ENGLISH/
COPY --from=chatscript-builder /src/ChatScript/LIVEDATA/SYSTEM /opt/ChatScript/LIVEDATA/SYSTEM
COPY --from=chatscript-builder /src/ChatScript/LIVEDATA/ENGLISH /opt/ChatScript/LIVEDATA/ENGLISH

COPY ./ChatScript/RAWDATA/files0.txt /opt/ChatScript/RAWDATA/files0.txt
COPY ./ChatScript/RAWDATA/ONTOLOGY /opt/ChatScript/RAWDATA/ONTOLOGY/
COPY ./ChatScript/RAWDATA/WORLDDATA /opt/ChatScript/RAWDATA/WORLDDATA/
COPY ./ChatScript/RAWDATA/QUIBBLE /opt/ChatScript/RAWDATA/QUIBBLE/

COPY ./ChatScript/RAWDATA/files${BOTNAME}.txt /opt/ChatScript/RAWDATA/files${BOTNAME}.txt
COPY ./ChatScript/RAWDATA/${BOTNAME} /opt/ChatScript/RAWDATA/${BOTNAME}/

RUN mkdir /opt/ChatScript/TOPIC

WORKDIR /opt/ChatScript/BINARIES

# Make binary executable
RUN chmod +x LinuxChatScript64

RUN ./LinuxChatScript64 local build0=files0.txt
RUN ./LinuxChatScript64 local build1=files${BOTNAME}.txt

FROM ubuntu:18.04 as chatscript

RUN apt-get --yes update \
 && apt-get --no-install-recommends --yes install libcurl3 \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=chatscript-builder-bot /opt/ChatScript ChatScript/

VOLUME /app/ChatScript/RAWDATA
VOLUME /app/ChatScript/LOGS
VOLUME /app/ChatScript/USERS

# Make binary executable
RUN chmod +x ChatScript/BINARIES/LinuxChatScript64

WORKDIR /app/ChatScript/BINARIES

EXPOSE 1024

ENTRYPOINT ["./LinuxChatScript64"]