// <auto-generated />
using System;
using IanByrne.ResearchProject.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(PostMortemContext))]
    [Migration("20201015190022_AddObjectivesFacts")]
    partial class AddObjectivesFacts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IanByrne.ResearchProject.Shared.Models.Bot", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Bots");

                    b.HasData(
                        new
                        {
                            Id = 1u,
                            Name = "Reggie"
                        },
                        new
                        {
                            Id = 2u,
                            Name = "Cow"
                        },
                        new
                        {
                            Id = 3u,
                            Name = "Olive"
                        },
                        new
                        {
                            Id = 4u,
                            Name = "Clarence"
                        });
                });

            modelBuilder.Entity("IanByrne.ResearchProject.Shared.Models.ObjectiveEntity", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<bool>("Done")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequiredFacts")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Target")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<uint?>("UserId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Objectives");
                });

            modelBuilder.Entity("IanByrne.ResearchProject.Shared.Models.Survey", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("Q1")
                        .HasColumnType("int");

                    b.Property<int>("Q10")
                        .HasColumnType("int");

                    b.Property<int>("Q11")
                        .HasColumnType("int");

                    b.Property<int>("Q12")
                        .HasColumnType("int");

                    b.Property<int>("Q13")
                        .HasColumnType("int");

                    b.Property<int>("Q14")
                        .HasColumnType("int");

                    b.Property<int>("Q15")
                        .HasColumnType("int");

                    b.Property<int>("Q16")
                        .HasColumnType("int");

                    b.Property<int>("Q17")
                        .HasColumnType("int");

                    b.Property<int>("Q18")
                        .HasColumnType("int");

                    b.Property<int>("Q19")
                        .HasColumnType("int");

                    b.Property<int>("Q2")
                        .HasColumnType("int");

                    b.Property<int>("Q20")
                        .HasColumnType("int");

                    b.Property<int>("Q21")
                        .HasColumnType("int");

                    b.Property<int>("Q22")
                        .HasColumnType("int");

                    b.Property<int>("Q23")
                        .HasColumnType("int");

                    b.Property<int>("Q24")
                        .HasColumnType("int");

                    b.Property<int>("Q25")
                        .HasColumnType("int");

                    b.Property<int>("Q26")
                        .HasColumnType("int");

                    b.Property<int>("Q27")
                        .HasColumnType("int");

                    b.Property<int>("Q28")
                        .HasColumnType("int");

                    b.Property<int>("Q29")
                        .HasColumnType("int");

                    b.Property<int>("Q3")
                        .HasColumnType("int");

                    b.Property<int>("Q30")
                        .HasColumnType("int");

                    b.Property<int>("Q31")
                        .HasColumnType("int");

                    b.Property<int>("Q4")
                        .HasColumnType("int");

                    b.Property<int>("Q5")
                        .HasColumnType("int");

                    b.Property<int>("Q6")
                        .HasColumnType("int");

                    b.Property<int>("Q7")
                        .HasColumnType("int");

                    b.Property<int>("Q8")
                        .HasColumnType("int");

                    b.Property<int>("Q9")
                        .HasColumnType("int");

                    b.Property<uint>("UserId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("IanByrne.ResearchProject.Shared.Models.Transcript", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("BotId")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<uint?>("UserId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("BotId");

                    b.HasIndex("UserId");

                    b.ToTable("Transcripts");
                });

            modelBuilder.Entity("IanByrne.ResearchProject.Shared.Models.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<Guid>("CookieId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Facts")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("GameMode")
                        .HasColumnType("int");

                    b.Property<bool>("UsedDevCommand")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("WinDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IanByrne.ResearchProject.Shared.Models.ObjectiveEntity", b =>
                {
                    b.HasOne("IanByrne.ResearchProject.Shared.Models.User", "User")
                        .WithMany("Objectives")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IanByrne.ResearchProject.Shared.Models.Survey", b =>
                {
                    b.HasOne("IanByrne.ResearchProject.Shared.Models.User", "User")
                        .WithOne("Survey")
                        .HasForeignKey("IanByrne.ResearchProject.Shared.Models.Survey", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IanByrne.ResearchProject.Shared.Models.Transcript", b =>
                {
                    b.HasOne("IanByrne.ResearchProject.Shared.Models.Bot", "Bot")
                        .WithMany("Transcripts")
                        .HasForeignKey("BotId");

                    b.HasOne("IanByrne.ResearchProject.Shared.Models.User", "User")
                        .WithMany("Transcripts")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
